services:
  mongo:
    image: mongo:7
    container_name: mongo-db
    ports: 
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Admin
      - MONGO_INITDB_ROOT_PASSWORD=Mongo_MDP123456789
    volumes:
      - mongo_db:/data/db

  nifi:
    image: apache/nifi:1.26.0
    container_name: Apache_nifi
    ports: 
      - 8443:8443
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=Siri
      - SINGLE_USER_CREDENTIALS_PASSWORD=Nifi_MDP123456789#
    depends_on:
      - mongo
    volumes:
      - nifi_home:/opt/nifi/nifi-current

  trino:
    image: trinodb/trino:463
    container_name: Trino
    ports: 
      - 8082:8080
    environment:
      - CATALOG_MANAGEMENT=dynamic
    depends_on:
      - mongo
    volumes:
      - ./mongo.properties:/etc/trino/catalog/mongo.properties
      - trino_catalog:/etc/trino/catalog


volumes: 
  mongo_db:
  nifi_home:
  trino_catalog:
